[package]
name = "warp_dsl"
version = "0.1.0"
authors = ["ayosec@gmail.com"]

[dependencies]
warp = "0.1"

[dev-dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
pretty_env_logger = "*"
